export const TOGGLE_SAMPLE_DISPLAY_STATUS = "TOGGLE_SAMPLE_DISPLAY_STATUS";
export const GET_COMPONENTS_FROM_METADATA = "GET_COMPONENTS_FROM_METADATA";
export const RELOAD_COMPONENT = "RELOAD_COMPONENT";
